select EPS_P1
from RES_COM_PFT_FCST
where RES_ID in (
select RES_ID 
FROM RES_REPORT_MAIN
WHERE INNER_CODE in (
select INNER_CODE 
FROM STK_CODE
WHERE 	STOCKCODE = '000001'
)
AND WRITEDATE 
BETWEEN '2015-06-01' 
AND '2015-12-01')
AND EPS_P1 is not NULL
#)