#SELECT EXPECT_PRICE FROM RES_COM_INVEST_RATING WHERE RES_ID IN ( SELECT RES_ID FROM RES_REPORT_MAIN WHERE INNER_CODE = '101000001' AND WRITEDATE BETWEEN '2013-07-02' AND '2014-01-02')
#SELECT RES_COM_INVEST_RATING.EXPECT_PRICE,WRITEDATE FROM RES_REPORT_MAIN INNER join RES_COM_INVEST_RATING On RES_COM_INVEST_RATING.RES_ID =RES_REPORT_MAIN.RES_ID where RES_REPORT_MAIN.INNER_CODE = '101000001' AND WRITEDATE BETWEEN '2013-07-02' AND '2014-01-02';
#SELECT * FROM res_expect_pe LIMIT 10;
#SELECT F1Y FROM RES_EXPECT_PE WHERE  INNER_CODE= '101000001' AND FORECAST_YEAR = '2016' AND STAT_PERIOD = '六个月';
#SELECT  F1Y FROM RES_EXPECT_PE WHERE INNER_CODE IN (SELECT INNER_CODE FROM stk_code where STOCKCODE='000001') AND  FORECAST_YEAR = '2016' AND STAT_PERIOD = '六个月';
SELECT F1Y FROM RES_EXPECT_PE INNER JOIN stk_code ON res_expect_pe.INNER_CODE=stk_code.INNER_CODE where stk_code.STOCKCODE='000001' AND  FORECAST_YEAR = '2016' AND STAT_PERIOD = '六个月';